# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(378, 158)
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setGeometry(QtCore.QRect(250, 60, 111, 16))
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(130, 60, 111, 16))
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 111, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_4.setObjectName("label_4")
        self.RoastEdit = QtWidgets.QLineEdit(parent=Form)
        self.RoastEdit.setGeometry(QtCore.QRect(130, 30, 113, 22))
        self.RoastEdit.setObjectName("RoastEdit")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(250, 10, 111, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_3.setObjectName("label_3")
        self.MassEdit = QtWidgets.QLineEdit(parent=Form)
        self.MassEdit.setGeometry(QtCore.QRect(250, 80, 113, 22))
        self.MassEdit.setObjectName("MassEdit")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(130, 10, 111, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_2.setObjectName("label_2")
        self.BeansEdit = QtWidgets.QLineEdit(parent=Form)
        self.BeansEdit.setGeometry(QtCore.QRect(250, 30, 113, 22))
        self.BeansEdit.setObjectName("BeansEdit")
        self.DescEdit = QtWidgets.QLineEdit(parent=Form)
        self.DescEdit.setGeometry(QtCore.QRect(10, 80, 113, 22))
        self.DescEdit.setObjectName("DescEdit")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label.setObjectName("label")
        self.OKButton = QtWidgets.QPushButton(parent=Form)
        self.OKButton.setGeometry(QtCore.QRect(10, 110, 361, 40))
        self.OKButton.setObjectName("OKButton")
        self.VarEdit = QtWidgets.QLineEdit(parent=Form)
        self.VarEdit.setGeometry(QtCore.QRect(10, 30, 113, 22))
        self.VarEdit.setObjectName("VarEdit")
        self.CoastEdit = QtWidgets.QLineEdit(parent=Form)
        self.CoastEdit.setGeometry(QtCore.QRect(130, 80, 113, 22))
        self.CoastEdit.setObjectName("CoastEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_7.setText(_translate("Form", "Mass"))
        self.label_6.setText(_translate("Form", "Coast"))
        self.label_4.setText(_translate("Form", "Describe"))
        self.label_3.setText(_translate("Form", "Beans"))
        self.label_2.setText(_translate("Form", "Roast"))
        self.label.setText(_translate("Form", "Varietie"))
        self.OKButton.setText(_translate("Form", "Добавить"))
